x-gpu-config:
  &gpu-config
  runtime: nvidia
  environment:
    - DISPLAY=${DISPLAY:?err}
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all

x-cpu-config:
  &cpu-config
  environment:
    - DISPLAY=${DISPLAY:?err}
    - LIBGL_ALWAYS_SOFTWARE=1

services:
  rosbot_sim:
    image: rosbot
    container_name: rosbot_sim
    build:
      context: .
      dockerfile: Dockerfile
    <<: [*gpu-config]
    user: davood
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./tutorial_pkg:/ros2_ws/src/tutorial_pkg:rw
    tty: true
    stdin_open: true
    entrypoint: /bin/bash
    networks:
      rosbot_network:
        ipv4_address: 192.168.32.2


  rosbot_client:
    depends_on: 
      - rosbot_sim
    image: rosbot
    container_name: rosbot_client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    <<: [*gpu-config]
    tty: true
    stdin_open: true
    entrypoint: /bin/bash
    networks:
      rosbot_network:
        ipv4_address: 192.168.32.3
    

networks:
  rosbot_network:
    name: rosbot_network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.32.0/24